version: 2.1
# orbs - reusable packages for use
orbs:
  node: circleci/node@5.0.1
  docker: circleci/docker@2.1.4
  heroku: circleci/docker@2.0.0
# jobs - set of instructions / functions
jobs:
  build: # job name
    docker: # environment
      - image: cimg/node:16.10
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run : |
          echo "Installing dependencies..."
          npm install
  test: 
    docker:
      - image: cimg/node:16.10
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run : |
          echo "Running tests..."
          npm run test
  publish: #also known as the build-and-push
    executor: docker/docker #define the execution environment in which the steps of a job will run.
    steps:
      - setup_remote_docker
      - checkout
      - docker/check
      - docker/build: #build the image
          image: terencegaffudsu/education-space
          # Mini activity #3 - add a tag called v1.0.1 and push the tag in docker hub
      - docker/push: #pushes the image to the specified account in the environment variables
          image: terencegaffudsu/education-space
  deploy:
    docker:
      - image: cimg/node:16.10
    steps:
      - setup_remote_docker
      - heroku/install
      - checkout
      - run: 
          name: Heroku Container Push
          commands: |
            heroku container:login
            heroku container:push web -a terence-su-devops
            heroku container:release web -a terence-su-devops

# workflow - defines what sequence will the jobs run
workflows:
  simple_workflow: # workflow name
    jobs:
      - build
      - test:
          requires:
            - build
      #Mini activity #2 - how to make the publish job execute after the test job?
      - publish:
          requires:
            - test
      - deploy:
          requires:
            - publish